language: node_js

node_js:
  - 14

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t fer/simple-node-travis .


deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master