language: node_js

node_js:
  - 14

services:
  - docker

script:
  - docker --version
  - docker build -t simple-node-travis .
  - docker tag simple-node nanotorre/simple-node-travis:latest


after-success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push nanotorre/simple-node-travis:latest